<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from "vue";

const samples = [
  { phrase: "hello there", audio: "/hello_there.wav", note: "A warm, two-word greeting" },
  { phrase: "curious?", audio: "/bare_question.wav", note: "An inquisitive terminal rise" },
  { phrase: "cat", audio: "/cat.wav", note: "A compact noun signature" },
  { phrase: "airplane", audio: "/airplane.wav", note: "A longer semantic gesture" },
];
const selected = ref(0);
const playing = ref(false);
let audio: HTMLAudioElement | undefined;
const sample = computed(() => samples[selected.value]);

function play() {
  audio?.pause();
  audio = new Audio(sample.value.audio);
  playing.value = true;
  audio.addEventListener("ended", () => (playing.value = false), { once: true });
  audio.play().catch(() => (playing.value = false));
}

function choose(index: number) {
  selected.value = index;
  play();
}

onBeforeUnmount(() => audio?.pause());
</script>

<template>
  <section id="signal-console" class="console" aria-labelledby="console-title">
    <div class="console-heading">
      <p class="eyebrow">Live archive / authentic VOICE_V12 renders</p>
      <h2 id="console-title">Hear what<br /><em>meaning</em> sounds like.</h2>
      <p>
        Choose a transmission. Each recording is a golden fixture generated by the real Rust
        engine—not a browser imitation.
      </p>
    </div>
    <div class="console-panel">
      <div class="scope" :class="{ active: playing }" aria-hidden="true">
        <span
          v-for="bar in 38"
          :key="bar"
          :style="{ '--bar': `${16 + ((bar * 17) % 68)}%`, '--delay': `${(bar % 9) * -0.07}s` }"
        />
        <i>VOICE<br />V12</i>
      </div>
      <div class="readout">
        <span>Input phrase</span><strong>“{{ sample.phrase }}”</strong
        ><small>{{ sample.note }}</small>
      </div>
      <button class="play" type="button" @click="play">
        <span>{{ playing ? "■" : "▶" }}</span
        >{{ playing ? "Transmitting" : "Play transmission" }}
      </button>
      <div class="presets" aria-label="Sample transmissions">
        <button
          v-for="(item, index) in samples"
          :key="item.phrase"
          type="button"
          :class="{ selected: index === selected }"
          @click="choose(index)"
        >
          <span>0{{ index + 1 }}</span
          >{{ item.phrase }}
        </button>
      </div>
      <p class="console-note">
        To translate anything, install the CLI: <code>dootdoot "your words"</code>
        <a href="/usage">Get started →</a>
      </p>
    </div>
  </section>
</template>
